spring.application.name=matchmaking-service
server.port=8085

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=123456
spring.data.redis.database=1
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.admin.fail-fast=false
spring.mvc.async.request-timeout=120000

game.kafka.match-topic=match.create
