using System.Collections;
using System.Text;
using TMPro;
using UnityEngine;
using UnityEngine.Networking;
using UnityEngine.SceneManagement;

public class AuthSessionRuntime : MonoBehaviour
{
    public static AuthSessionRuntime Instance { get; private set; }

    [Header("UI Runtime")]
    public GameObject warningPanel;
    public UnityEngine.UI.Button okButton;

    [Header("Auth Settings")]
    public string logoutApiPath = "/api/auth/logout";
    public string loginSceneName = "Authentication";
    public int defaultCountdownSeconds = 10;

    [Header("Session Polling")]
    public string refreshApiPath = "/api/auth/refresh";
    private float sessionPollIntervalSec = 3f; // Giảm từ 30s xuống 3s để nhận diện duplicate login cực nhạy

    private bool _isHandlingForceLogout;
    private bool _userClickedOk;

    // Tự động khởi tạo khi game load, đảm bảo session check luôn hoạt động mà không cần kéo component thủ công
    [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]
    private static void AutoInitialize()
    {
        if (Instance == null)
        {
            GameObject go = new GameObject("AuthSessionRuntime_AutoGenerated");
            go.AddComponent<AuthSessionRuntime>();
            Debug.Log("[AuthSession] Tự động kích hoạt AuthSessionRuntime trong game.");
        }
    }

    private void Awake()
    {
        if (Instance != null && Instance != this)
        {
            Destroy(gameObject);
            return;
        }

        Instance = this;
        DontDestroyOnLoad(gameObject);
        StartCoroutine(SessionPollLoop());
    }

    private IEnumerator SessionPollLoop()
    {
        while (true)
        {
            yield return new WaitForSeconds(sessionPollIntervalSec);

            if (_isHandlingForceLogout) continue;

            string jwt          = GameApiClient.GetJwt();
            string refreshToken = GameApiClient.GetRefreshToken();
            if (string.IsNullOrEmpty(jwt) || string.IsNullOrEmpty(refreshToken)) continue;

            // Bọc toàn bộ trong try-catch để coroutine polling KHÔNG BAO GIỜ bị crash vĩnh viễn
            yield return StartCoroutine(SafeRefreshSession(refreshToken));
        }
    }

    private IEnumerator SafeRefreshSession(string refreshToken)
    {
        string body = $"{{\"refreshToken\":\"{refreshToken}\"}}";
        using (var req = GameApiClient.CreateRequest(refreshApiPath, "POST", body))
        {
            yield return req.SendWebRequest();

            try
            {
                if (req.result == UnityWebRequest.Result.Success)
                {
                    string responseText = req.downloadHandler != null ? req.downloadHandler.text : "";
                    string newJwt     = ExtractJsonField(responseText, "jwt");
                    string newRefresh = ExtractJsonField(responseText, "refreshToken");
                    
                    if (!string.IsNullOrEmpty(newJwt))
                        GameApiClient.SetJwt(newJwt);
                    if (!string.IsNullOrEmpty(newRefresh))
                        GameApiClient.SetRefreshToken(newRefresh);
                    PlayerPrefs.Save();
                    
                }
                else if (req.result == UnityWebRequest.Result.ConnectionError)
                {
                    Debug.LogWarning($"[AuthSession] Không thể kiểm tra session do lỗi kết nối mạng (Hãy check IP LAN nếu bật LAN mode): {req.error}");
                }
                else
                {
                    // Lỗi giao thức HTTP (400, 401, 403, 500...) -> session bị hủy ở server
                    long statusCode = req.responseCode;
                    string errBody = req.downloadHandler != null ? req.downloadHandler.text : "";
                    Debug.Log($"[AuthSession] PHÁT HIỆN SESSION BỊ HỦY! HTTP {statusCode}: {req.error}\nPhản hồi server: {errBody}");
                    
                    // Thực hiện kick người chơi cũ ra ngay lập tức
                    HandleForceLogout(1003, "Tài khoản của bạn đã được đăng nhập từ một thiết bị khác.");
                }
            }
            catch (System.Exception ex)
            {
                Debug.LogError($"[AuthSession] Lỗi xảy ra trong quá trình xử lý session refresh: {ex.Message}\n{ex.StackTrace}");
            }
        }
    }

    private static string ExtractJsonField(string json, string key)
    {
        string search = $"\"{key}\":\"";
        int start = json.IndexOf(search, System.StringComparison.Ordinal);
        if (start < 0) return null;
        start += search.Length;
        int end = json.IndexOf('"', start);
        return end < 0 ? null : json.Substring(start, end - start);
    }

    private void OnApplicationQuit()
    {
        AuthenticationUIManager.LogoutSilently(this, GameApiClient.BuildUrl(logoutApiPath));
        AuthenticationUIManager.ClearLocalAuth();
    }

    public void HandleForceLogout(int code, string message, int countdownSec = -1)
    {
        if (_isHandlingForceLogout) return;
        int seconds = countdownSec > 0 ? countdownSec : defaultCountdownSeconds;
        StartCoroutine(ForceLogoutFlow(code, message, seconds));
    }

    public void TriggerDuplicateLoginKickTest()
    {
        HandleForceLogout(1003, "Tài khoản đã đăng nhập ở nơi khác", defaultCountdownSeconds);
    }

    /// <summary>
    /// Đảm bảo giao diện cảnh báo luôn khả dụng. Nếu bị null hoặc bị hủy do chuyển scene,
    /// code sẽ tự tìm lại hoặc tự vẽ Canvas khẩn cấp ngay lúc runtime.
    /// </summary>
    private void EnsureWarningUI()
    {
        // 1. Kiểm tra xem tham chiếu cũ còn hợp lệ không
        if (warningPanel != null) return;

        // 2. Thử tìm trong Scene hiện tại
        GameObject found = GameObject.Find("WarningPanel");
        if (found != null)
        {
            warningPanel = found;
            okButton = found.GetComponentInChildren<UnityEngine.UI.Button>();
            return;
        }

        // 3. Nếu hoàn toàn không có, tự vẽ Canvas khẩn cấp lúc runtime
        GameObject canvasGo = new GameObject("AuthSession_EmergencyCanvas");
        Canvas canvas = canvasGo.AddComponent<Canvas>();
        canvas.renderMode = RenderMode.ScreenSpaceOverlay;
        canvas.sortingOrder = 9999; // Đảm bảo đè lên mọi thứ khác
        canvasGo.AddComponent<UnityEngine.UI.CanvasScaler>();
        canvasGo.AddComponent<UnityEngine.UI.GraphicRaycaster>();
        DontDestroyOnLoad(canvasGo);

        // Tạo Background Panel đen mờ
        GameObject panelGo = new GameObject("EmergencyWarningPanel");
        panelGo.transform.SetParent(canvasGo.transform, false);
        var image = panelGo.AddComponent<UnityEngine.UI.Image>();
        image.color = new Color(0.1f, 0.1f, 0.1f, 0.95f);
        
        var rectTransform = panelGo.GetComponent<RectTransform>();
        rectTransform.anchorMin = Vector2.zero;
        rectTransform.anchorMax = Vector2.one;
        rectTransform.sizeDelta = Vector2.zero;

        // Tạo Text hiển thị thông báo
        GameObject textGo = new GameObject("WarningText");
        textGo.transform.SetParent(panelGo.transform, false);
        var textComponent = textGo.AddComponent<TextMeshProUGUI>();
        textComponent.fontSize = 26;
        textComponent.alignment = TextAlignmentOptions.Center;
        textComponent.color = Color.red;
        
        var textRect = textGo.GetComponent<RectTransform>();
        textRect.sizeDelta = new Vector2(800, 300);

        // Tạo nút OK
        GameObject btnGo = new GameObject("OkButton");
        btnGo.transform.SetParent(panelGo.transform, false);
        var btnImage = btnGo.AddComponent<UnityEngine.UI.Image>();
        btnImage.color = new Color(0.2f, 0.6f, 0.2f, 1f);
        var btnComponent = btnGo.AddComponent<UnityEngine.UI.Button>();
        
        var btnRect = btnGo.GetComponent<RectTransform>();
        btnRect.sizeDelta = new Vector2(200, 60);
        btnRect.anchoredPosition = new Vector2(0, -100);

        GameObject btnTextGo = new GameObject("Text");
        btnTextGo.transform.SetParent(btnGo.transform, false);
        var btnText = btnTextGo.AddComponent<TextMeshProUGUI>();
        btnText.text = "OK";
        btnText.fontSize = 24;
        btnText.alignment = TextAlignmentOptions.Center;
        btnText.color = Color.white;
        var btnTextRect = btnTextGo.GetComponent<RectTransform>();
        btnTextRect.sizeDelta = new Vector2(200, 60);

        warningPanel = panelGo;
        okButton = btnComponent;
    }

    private IEnumerator ForceLogoutFlow(int code, string message, int countdownSeconds)
    {
        _isHandlingForceLogout = true;

        // Đảm bảo Warning UI hoạt động
        EnsureWarningUI();

        if (warningPanel != null)
            warningPanel.SetActive(true);

        _userClickedOk = false;
        if (okButton != null)
        {
            okButton.onClick.RemoveAllListeners();
            okButton.onClick.AddListener(() => { _userClickedOk = true; });
        }

        while (!_userClickedOk)
        {
            yield return null;
        }

        // Chỉ gọi logout lên server nếu KHÔNG phải bị đuổi do duplicate login.
        // Khi bị kick do duplicate login (code 1003), session đã thuộc về người đăng nhập mới.
        // Nếu gọi logout ở đây sẽ hủy luôn session của người mới → cả hai đều bị kick.
        if (code != 1003)
        {
            AuthenticationUIManager.LogoutSilently(this, GameApiClient.BuildUrl(logoutApiPath));
        }
        AuthenticationUIManager.ClearLocalAuth();

        yield return new WaitForSeconds(0.2f);

        // Ẩn panel cảnh báo thay vì hủy để tái sử dụng sạch sẽ
        if (warningPanel != null)
            warningPanel.SetActive(false);

        if (!string.IsNullOrEmpty(loginSceneName))
            SceneManager.LoadScene(loginSceneName);

        _isHandlingForceLogout = false;
    }
}
