# 1. Kết nối MySQL (Đã thêm allowPublicKeyRetrieval để sửa lỗi Public Key)
spring.datasource.url=jdbc:mysql://localhost:3307/shoptank_db?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Ts171201@

# 2. Cấu hình JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# XÓA dòng MySQL8Dialect cũ, thay bằng dòng này hoặc để trống để Hibernate tự nhận diện
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# 3. Cấu hình Server
server.port=8088
server.max-http-header-size=32768